### ISSUE TITLE
i586-poky-linux-gcc directory requirements

### ISSUE THREAD

**Issue by ssjoholm** [todorez/galileo-linux-stable#1]
I have tried to compile the Galileo-Linux-Stable according to the instructions in the readme file, but I get stuck in the make command on step 2.

root@ubuntu:# ARCH=i386 LOCALVERSION= CROSS_COMPILE=i586-poky-linux- make -j8
make: i586-poky-linux-gcc: Command not found
...

Which causes the make to fail, when looking closer at the "i586-poky-linux-gcc", I have problem executing the binary file.

root@ubuntu:# ./i586-poky-linux-gcc
-bash: ./i586-poky-linux-gcc: No such file or directory
root@ubuntu:#

When testing with readelf, I can see that it is looking for a file in a directory that does not exists.

root@ubuntu:# readelf -a i586-poky-linux-gcc | grep Req
      [Requesting program interpreter: /opt/iot-devkit/1.7.2/sysroots/x86_64-pokysdk-linux/lib/ld-linux-x86-64.so.2]
root@ubuntu:#

I have unpacked the IoT DevKit under /opt/build/ and the file that it is looking for is under that folder as seen below, but it is not looking for this location.

root@ubuntu:# find . -name ld-linux-x86-64.so.2
./iotdk-ide-linux/devkit-x86/sysroots/x86_64-pokysdk-linux/lib/ld-linux-x86-64.so.2
root@ubuntu:#

Workaround.
1. Create directory "/opt/iot-devkit/1.7.2/sysroots/"
2. Rsync the downloaded iotdk package to the dircectory
   $ rsync -avP /<your directory>/iotdk-ide-linux/devkit-x86/sysroots/ /opt/iot-devkit/1.7.2/sysroots/
3. Change the PATH to refrect the change.
   $ export PATH="/opt/iot-devkit/1.7.2/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux/:$PATH"

And then run the make again...

Regards,
Sebastian

**Comment by todorez** [comment]
Hello @ssjoholm,
I think I know what the problem is - the loader path is invalid for all binaries in 'devkit-x86'. Since the  directory where the SDK will be downloaded is not known in advance, the loader path has to be 'fixed' at a later stage. If you execute the 'devkit-launcher' script this will fix the interpreter paths and launch Eclipse. Just close Eclipse and things should work without having to create new directories.

**Comment by ssjoholm** [comment]
Ok, I am using remote machine with Ubuntu Server, so there is no gui available, so I need to handle it on the terminal level. But I guess my workaround is then acceptable.

**Comment by todorez** [comment]
Yes, your workaround will also work. Just for completeness, I think that even if one is running on a headless machine the 'devkit-launcher' script will still fix the paths but will fail to launch the IDE.

**Comment by todorez** [comment]
I added a note about devkit-launcher to README. 

@ssjoholm - Thank you for reporting this issue.

**Comment by ssjoholm** [comment]
Please note that, if the machine is headless and running example Ubuntu Server (without GUI) then running the "devkit-launcher" will not change the PATH, it will print it out, but does not seem to get it changed.

root@ubuntu:/opt/build/iotdk-ide-linux# printenv PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
root@ubuntun:/opt/build/iotdk-ide-linux# ./devkit-launcher
/opt/build/iotdk-ide-linux/.
Relocating SDK
Setting variables
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/build/iotdk-ide-linux/./devkit-x86/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux/
root@ubuntu:/opt/build/iotdk-ide-linux# gdk_mir_display_open
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Eclipse: Cannot open display:
Eclipse:
An error has occurred. See the log file
/opt/build/iotdk-ide-linux/eclipse-linux/configuration/1439048008963.log.

root@ubuntu:/opt/build/iotdk-ide-linux# printenv PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
root@ubuntu:/opt/build/iotdk-ide-linux#

I can use the path it is printing out and the set it manually with export PATH="<path>".

Regards,
Sebastian
