### ISSUE TITLE
Issue with intel_qrk_esram_test.c

### ISSUE THREAD

**Issue by ssjoholm** [todorez/galileo-linux-stable#2]
When running the make it will fail because an fault in the "intel_qrk_esram_test.c" file.

In file included from drivers/platform/x86/quark/intel_qrk_esram_test.c:20:0:
drivers/platform/x86/quark/intel_qrk_esram_test.c: In function 'intel_qrk_crctest':
include/linux/crc32.h:66:36: warning: statement with no effect [-Wunused-value]
 #define crc32(seed, data, length)  crc32_le(seed, (unsigned char const _)(data), length)
                                    ^
drivers/platform/x86/quark/intel_qrk_esram_test.c:85:2: note: in expansion of macro 'crc32'
  crc32(0, pdata, crcsize);
  ^
drivers/platform/x86/quark/intel_qrk_esram_test.c: In function 'intel_qrk_esram_test_probe':
drivers/platform/x86/quark/intel_qrk_esram_test.c:501:62: error: macro "**DATE**" might prevent reproducible builds [-Werror=date-time]
  printk(KERN_INFO "%s/%s/%s complete OK !!\n", **FUNCTION**, **DATE**,**TIME**);
                                                              ^
drivers/platform/x86/quark/intel_qrk_esram_test.c:501:71: error: macro "**TIME**" might prevent reproducible builds [-Werror=date-time]
  printk(KERN_INFO "%s/%s/%s complete OK !!\n", **FUNCTION**, **DATE**,**TIME**);
                                                                       ^
  CC      drivers/platform/x86/quark/intel_qrk_thermal.o
  LD [M]  drivers/ptp/ptp.o
  CC [M]  drivers/platform/x86/quark/intel_qrk_audio_ctrl.o
  CC      drivers/pwm/core.o
cc1: some warnings being treated as errors
scripts/Makefile.build:257: recipe for target 'drivers/platform/x86/quark/intel_qrk_esram_test.o' failed
make[4]: *_\* [drivers/platform/x86/quark/intel_qrk_esram_test.o] Error 1
make[4]: **\* Waiting for unfinished jobs....
  CC      drivers/pwm/sysfs.o
  CC      net/ipv4/xfrm4_protocol.o
  CC [M]  net/ipv4/ip_tunnel.o
  CC      drivers/pci/rom.o
  CC      drivers/pwm/pwm-lpss.o
  LD      drivers/pnp/pnpacpi/pnp.o
scripts/Makefile.build:402: recipe for target 'drivers/platform/x86/quark' failed
make[3]: **\* [drivers/platform/x86/quark] Error 2
scripts/Makefile.build:402: recipe for target 'drivers/platform/x86' failed
make[2]: **\* [drivers/platform/x86] Error 2
scripts/Makefile.build:402: recipe for target 'drivers/platform' failed
make[1]: **\* [drivers/platform] Error 2
make[1]: **\* Waiting for unfinished jobs....

It seems that the **DATE** and **TIME** is not defined anywhere and that will cause the failure. If they are removed it will work.

At line 501:

original:
printk(KERN_INFO "%s/%s/%s complete OK !!\n", **FUNCTION**, **DATE**,**TIME**);

changed to:
printk(KERN_INFO "%s/ complete OK !!\n", **FUNCTION**);

After this change the make (ARCH=i386 LOCALVERSION= CROSS_COMPILE=i586-poky-linux- make -j8) will be successful.

The original information regarding the workaround was found here: https://intel-openport-v7.hosted.jivesoftware.com/thread/77767

**Comment by todorez** [comment]
I see what the problem here is - gcc was upgraded to 4.9 in the latest release of devkit and the kernel prohibits the use of date-time if the compiler supports it. GCC 4.9 supports it so the build fails: 

Here is the original kernel commit:

commit fe7c36c7bde12190341722af69358e42171162f3
Author: Josh Triplett josh@joshtriplett.org
Date:   Mon Dec 23 13:56:06 2013 -0800

```
Makefile: Build with -Werror=date-time if the compiler supports it

GCC 4.9 and newer have a new warning -Wdate-time, which warns on any use
of __DATE__, __TIME__, or __TIMESTAMP__, which would make the build
non-deterministic.  Now that the kernel does not use any of those
macros, turn on -Werror=date-time if available, to keep it that way.

The kernel already (optionally) records this information at build time
in a single place; other kernel code should not duplicate that.

Signed-off-by: Josh Triplett <josh@joshtriplett.org>
Signed-off-by: Michal Marek <mmarek@suse.cz>
```

Removing DATE and TIME is the right fix here. Please feel free to send a patch to fix this.

**Comment by ssjoholm** [comment]
Fixed and pull request sent.
