### ISSUE TITLE
Question: Which linux distro is used as base?

### ISSUE THREAD

**Issue by ssjoholm** [todorez/galileo-linux-stable#3]
Hi,

I would like to know which Linux distro is used as base installation in the instructions? As the instructions is telling to replace existing bzImage with the new compiled, I would like to use same linux installation as base.

Regards,
Sebastian

**Comment by todorez** [comment]
There isn't a mainstream distro or package repository where you can download a kernel package. The image is built with Yocto. Take a look at the IoT DevKit and Yocto websites for more details.

**Comment by ssjoholm** [comment]
Yocto was the name I was looking for, thank you.
