### ISSUE TITLE
Status WRT modern kernels?

### ISSUE THREAD

**Issue by dmarkey** [todorez/galileo-linux-stable#9]
Hey there.

I know this project seems dead but maybe you can tell me:

1. Are all required changes in upstream?
2. If so, can an ordinary toolchain compile an i386 kernel that boots on Gen 1?

Some dude posted these configs he claims run on Quark: https://hansen.beer/~dave/linux/galileo/ I have had little success.

**Comment by todorez** [comment]
The current stable kernel should support it:

https://elixir.bootlin.com/linux/latest/source/arch/x86/Kconfig#L620

**Comment by dmarkey** [comment]
I see, do you know if it requires any special cmdline params to boot? This one is built using this config posted.

./arch/x86/boot/bzImage: Linux kernel x86 boot executable bzImage, version 5.10.27-galileo (root@master) #1 Sun Apr 4 15:07:11 UTC 2021, RO-rootFS, swap_dev 0x3, Normal VGA


And this grub entry:

```
title Test2
    root (hd0,0)
    kernel /bzImage root=/dev/ram0 console=ttyS1,115200n8 earlycon=uart8250,mmio32,$EARLY_CON_ADDR_REPLACE,115200n8 reboot=efi,warm apic=debug rw LABEL=boot debugshell=5 rootimage=image-full-galileo-clanton.ext3
```

Of course I don't expect it to work very well, but at boot I get literally nothing after it's selected by grub.. simply

```
[grub]
address=0xff800000
item_file=../../meta-clanton/yocto_build/tmp/deploy/images/grub.efi
sign=yes
fvwrap=yes
guid=B43BD3E1-64D1-4744-9394-D0E1C4DE8C87
type=mfh.bootloader_signed
svn_index=4


[Linux-EFI, setup=0x10cc, size=0x307d80]
```

and nothing. I'm thinking the console isn't being connected and I'm not seeing boot messages.

**Comment by todorez** [comment]
I have no idea to be honest. I haven't tried any of the upstream kernels on Galileo.

**Comment by dmarkey** [comment]
Ok thanks for the help!
